### ISSUE TITLE
Error building site: "bundler: failed to load command: jekyll"

### ISSUE THREAD

**Issue by MarkWieczorek** [tomjohnson1492/documentation-theme-jekyll#207]
I've been using this theme for a couple years now with only minor problems. Today I tried rebuilding my site, but I encountered an error that I've never seen before.

I am using macOS with brew, so the first thing I did was to reinstall ruby, jekyll and bundle. I then deleted the `Gemfile.lock` file and `vendor` folder. However, whenever I rebuild using `bundle exec jekyll serve` I get the following error:

```
docs git:(develop) ✗ bundler exec jekyll serve
Configuration file: /Users/lunokhod/SphericalHarmonics/shtools-git/docs/_config.yml
            Source: /Users/lunokhod/SphericalHarmonics/shtools-git/docs
       Destination: /Users/lunokhod/SphericalHarmonics/shtools-git/docs/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
   GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
                    done in 6.453 seconds.
 Auto-regeneration: enabled for '/Users/lunokhod/SphericalHarmonics/shtools-git/docs'
bundler: failed to load command: jekyll (/Users/lunokhod/SphericalHarmonics/shtools-git/docs/vendor/ruby/3.0.0/bin/jekyll)
/Users/lunokhod/SphericalHarmonics/shtools-git/docs/vendor/ruby/3.0.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve/servlet.rb:3:in `require': cannot load such file -- webrick (LoadError)
	from /Users/lunokhod/SphericalHarmonics/shtools-git/docs/vendor/ruby/3.0.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve/servlet.rb:3:in `<top (required)>'
[...]
```
Does anyone have an idea of what the problem might be? (The github warning is irrelevant.)

**Comment by MarkWieczorek** [comment]
This might be an issue with Ruby 3.0.0: I tried rebuilding using Ruby 2.7 and it works. :)
