### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by kerim** [tomjohnson1492/documentation-theme-jekyll#52]
I'm following the [instructions](http://idratherbewriting.com/documentation-theme-jekyll/index.html)  to install this on my Mac (using Option 2 for use with github pages), but I get the following error:

```
  Liquid Exception: cannot load such file -- rouge in pages/mydoc/mydoc_help_api.md
bundler: failed to load command: jekyll (/usr/local/bin/jekyll)
LoadError: cannot load such file -- rouge
  /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/tags/highlight.rb:102:in `require'
  /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/tags/highlight.rb:102:in `render_rouge'
  /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/tags/highlight.rb:53:in `render'
  /usr/local/lib/ruby/gems/2.3.0/gems/liquid-2.6.1/lib/liquid/block.rb:109:in `block in render_all'
  /usr/local/lib/ruby/gems/2.3.0/gems/liquid-2.6.1/lib/liquid/block.rb:96:in `each'
  /usr/local/lib/ruby/gems/2.3.0/gems/liquid-2.6.1/lib/liquid/block.rb:96:in `render_all'
  /usr/local/lib/ruby/gems/2.3.0/gems/liquid-2.6.1/lib/liquid/block.rb:82:in `render'
  /usr/local/lib/ruby/gems/2.3.0/gems/liquid-2.6.1/lib/liquid/template.rb:128:in `render'
  /usr/local/lib/ruby/gems/2.3.0/gems/liquid-2.6.1/lib/liquid/template.rb:138:in `render!'
  /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/convertible.rb:106:in `render_liquid'
  /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/convertible.rb:233:in `do_layout'
  /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/page.rb:122:in `render'
  /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:269:in `block in render'
  /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:268:in `each'
  /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:268:in `render'
  /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:46:in `process'
  /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/command.rb:28:in `process_site'
  /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:55:in `build'
  /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:33:in `process'
  /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/commands/serve.rb:25:in `block (2 levels) in init_with_program'
  /usr/local/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /usr/local/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /usr/local/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /usr/local/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /usr/local/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-2.4.0/bin/jekyll:18:in `<top (required)>'
  /usr/local/bin/jekyll:22:in `load'
  /usr/local/bin/jekyll:22:in `<top (required)>'
```

I tried "gem install rouge", "bundle update", etc. but nothing seemed to help. What should I do?

**Comment by nghiacc** [comment]
I got this issue as well

**Comment by tomjoht** [comment]
This should be fixed now. For some reason, the github-pages gem isn't allowing me to use the `highlight` tag. I removed the `highlight` tag on the problematic pages (mydoc_syntax_highlighting and mydoc_help_api), and updated the Gemfiles. This seemed to fix the issue. Can you let me know if this fixed the issue for you?

**Comment by kerim** [comment]
Seems to be fixed. Thanks!
